apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: {{ .Release.Namespace }}
  labels:
    app: django
spec:
  type: {{ .Values.django.service.type }}
  selector:
    app: django
  ports:
    - name: http
      port: {{ .Values.django.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.django.service.type "NodePort") .Values.django.service.nodePort }}
      nodePort: {{ .Values.django.service.nodePort }}
      {{- end }}
